#pragma once

#include <cstddef>

namespace nvidia_app_cleaner {

enum class UiLanguage {
    english,
    simplified_chinese,
};

enum class TextId : std::size_t {
    window_title,
    unknown_error,
    windows_error_prefix,
    service_invalid_state,
    service_timeout,
    channel_game_ready,
    channel_studio,
    category_game_ready,
    category_studio,
    category_app_update,
    category_legacy_update,
    category_legacy_downloader,
    column_category,
    column_location,
    column_size,
    column_status,
    state_found,
    state_empty,
    state_not_found,
    state_access_error,
    state_unsafe_path,
    state_partial,
    state_unknown,
    button_scan_again,
    button_repair_stuck,
    button_settings,
    button_save,
    button_back,
    status_scanning,
    program_data_missing,
    status_read_only_prefix,
    status_read_only_suffix,
    status_repair_available,
    app_still_running,
    service_pause_failed,
    framework_missing,
    local_app_data_missing,
    backup_label,
    service_restart_label,
    stale_state_disappeared,
    repair_not_completed,
    successful_repairs_label,
    repair_succeeded,
    executable_missing,
    repair_process_failed,
    exit_app_first,
    no_stale_record,
    repair_candidates_intro,
    repair_confirmation,
    repair_dialog_title,
    settings_page_title,
    settings_description,
    settings_always_run_as_administrator,
    settings_saved,
    settings_read_failed,
    settings_write_failed,
    automatic_elevation_failed,
    category_installer2,
    category_ngx_models,
    button_clean_selected,
    program_files_missing,
    cleanup_no_selection,
    cleanup_confirmation_intro,
    cleanup_confirmation_suffix,
    cleanup_driver_warning,
    cleanup_installer2_warning,
    cleanup_ngx_warning,
    cleanup_dialog_title,
    cleanup_process_failed,
    cleanup_succeeded,
    cleanup_partial,
    cleanup_failed,
    cleanup_removed_prefix,
    cleanup_removed_suffix,
    cleanup_exit_app_first,
    cleanup_service_pause_failed,
    cleanup_no_changes,
    main_heading,
    main_description,
    button_select_recommended,
    button_clear_selection,
    summary_available_prefix,
    summary_selected_prefix,
    status_scan_complete,
    current_driver_scanning,
    current_driver_prefix,
    current_driver_not_detected,
    package_versions_prefix,
    navigation_repair,
    repair_page_description,
    repair_candidates_none,
    repair_candidates_count_prefix,
    cleanup_group_recommended,
    cleanup_group_optional,
    cleanup_group_rollback_drivers,
    about_content,
    count,
};

[[nodiscard]] UiLanguage system_ui_language();
[[nodiscard]] const wchar_t *text(UiLanguage language, TextId id);

} // namespace nvidia_app_cleaner
